import Head from "next/head";
import React from "react";

export default function Home({}) {
  return (
    <div>
      <Head>
        <title>The awsm App</title>
        <meta name="description" content="Generated by Bun.js" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full h-full">
        <div className="flex w-screen justify-left h-1/6">
          <h1 className="font-extrabold text-5xl cursor-pointer mx-12 mt-1.5 mb-3">
            awsm
          </h1>
        </div>
        <div className="flex w-screen h-4/6 bg-slate-500">
          <h1>Click ME</h1>
        </div>
        
      </main>
    </div>
  );
}
